export const UPDATE_CURRENT_PATH = "UPDATE_CURRENT_PATH";

export const ADD_EXPLORER_ITEM = "ADD_EXPLORER_ITEM";

export const DELETE_EXPLORER_ITEM = "DELETE_EXPLORER_ITEM";

export const HANDLE_DUPLICATE_DATA = "HANDLE_DUPLICATE_DATA";

export const UPDATE_QUERY = "UPDATE_QUERY";
